eval_n_to_sample: 100000
eval_cond_min: -0.2
eval_cond_max: 1.2
eval_n_categories: 10
eval_batch_size: 1000000

ckpt: 'band_contrastive/checkpoints/2025-09-24_20-32-18/best.pt'

# fn_simulation_settings: 'band_contrastive/configs/simulation_settings.json'