# name: cvae_vectors
defaults:
  - override /data: default_data
  - override /model: cvae_vector
  - override /loss: band_supcon
  - override /train: train_vector
  - override /eval: hitrate
  - override /optim: adam
seed: 0
device: gpu
log_dir: outputs/${now:%Y-%m-%d}/${hydra.job.name}
