seed: 12

epochs: 2000
batch_size: 256
lr: 1e-3
patience: 1500
log_every_n_steps: 5
check_val_every_n_epochs: 10
save_model: True

threshold_early_val_acc: 0.98
accuracy_func: 'regression'

use_dropout: False
dropout_rate: 0.1
clip_grad: False
